spring:
  mail:
    username: @gmail.com
    password: fuckoff
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

supplier:
  email: my@email

server:
  port: 8081