spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
        ddl-auto: auto
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    username: ${APP_EMAIL}
    password: ${APP_EMAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
key:
  access: ${KEY_ACCESS}
  refresh: ${KEY_REFRESH}
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: PT1H  # Cache period, например, 1 час
        cachecontrol:
          max-age: 3600  # Max-age для кэширования в секундах
          no-transform: true
          must-revalidate: true


#-Dspring.profiles.active=dev