spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/g_37_jp_shop
    username: postgres
    driver-class-name: org.postgresql.Driver
    password:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
  mail:
    username: @gmail.com
    password:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
key:
  access: =
  refresh: =

logging:
  file:
    name: logs/log.log
  level:
    root: info

messages:
  hello: Hello from local application!